######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 1 03:56:07 2008
######################################################################

TEMPLATE = app

# Input
HEADERS += gameloop.h \
 connecttoserverdialog.h
FORMS += connecttoserverdialog.ui joinserverdialog.ui mainwindow.ui
SOURCES += gameloop.cpp main.cpp \
 connecttoserverdialog.cpp

QT += network

