######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 21 15:19:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qtestlib \
            

QT += xml \
      network

# Input
HEADERS += testparser.h \
           mocksocket.h \
           ../parser.h
SOURCES += testparser.cpp \
           mocksocket.cpp \
           ../parser.cpp
