######################################################################
# Automatically generated by qmake (2.01a) dom sep 27 14:35:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += opt_cardsets.h optionsdialog.h optionstab.h
FORMS += opt_cardsets.ui optionsdialog.ui
SOURCES += __main.cpp opt_cardsets.cpp optionsdialog.cpp optionstab.cpp
