######################################################################
# Automatically generated by qmake (2.01a) vie sep 25 20:14:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tar.h
SOURCES += main.cpp tar.cpp
